/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/gingerbread.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gingerbread.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={-0.206}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Box_Paper_0.geometry} material={materials.Paper} position={[-10.596, 0.296, 3.457]} rotation={[0, 0, -0.645]} scale={-0.049} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 15.24]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Ribbon_Ribbon_0.geometry} material={materials.Ribbon} position={[-0.296, -10.596, -12.531]} rotation={[0, 0, -0.645]} scale={-0.049} />
            </group>
          </group>
          <mesh geometry={nodes.Placation_JSquat_0.geometry} material={materials.JSquat} position={[-0.437, 3.6, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.718} />
        </group>
      </group>
      <group position={[2.308, -0.713, -1.086]} rotation={[-Math.PI / 2, 0, 0]} scale={0.127}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials['Ribbon.001']} />
        </group>
      </group>
      <group position={[2.437, -0.707, -0.574]} rotation={[1.605, 0, 0]} scale={-0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube_Body_0.geometry} material={materials.Body} position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_Body_0.geometry} material={materials.Body} position={[0, 183.124, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials['Material.015']} position={[0, 100, -99.172]} rotation={[-Math.PI / 2, 0, 0]} scale={[17.5, 3, 100]} />
          <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials['Material.015']} position={[0, 100, 99.172]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[17.5, 3, 100]} />
          <mesh geometry={nodes.Cube004_Material_0.geometry} material={materials['Material.015']} position={[-99.172, 100, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[17.5, 3, 100]} />
          <mesh geometry={nodes.Cube005_Material_0.geometry} material={materials['Material.015']} position={[99.172, 100, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[17.5, 3, 100]} />
          <mesh geometry={nodes.Cube006_Material_0.geometry} material={materials['Material.015']} position={[0, 244.373, 24.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube007_Material_0.geometry} material={materials['Material.015']} position={[24.273, 248.327, 0.059]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube008_Material_0.geometry} material={materials['Material.015']} position={[-24.343, 248.327, 0.059]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube009_Material_0.geometry} material={materials['Material.015']} position={[0, 244.373, -23.795]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube010_Material_0.geometry} material={materials['Material.015']} position={[0, 223.511, 9.81]} rotation={[-0.595, 0, Math.PI]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube011_Material_0.geometry} material={materials['Material.015']} position={[-8.547, 227.465, -0.599]} rotation={[-Math.PI / 2, -0.976, Math.PI / 2]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube012_Material_0.geometry} material={materials['Material.015']} position={[8.7, 227.465, -0.599]} rotation={[-Math.PI / 2, 0.976, -Math.PI / 2]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cube013_Material_0.geometry} material={materials['Material.015']} position={[0, 223.511, -10.154]} rotation={[-2.546, 0, 0]} scale={[100, 68, 40]} />
          <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials['Material.015']} position={[0, 247.614, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[40, 18, 100]} />
          <mesh geometry={nodes.Torus_Material_0.geometry} material={materials['Material.015']} position={[0, 205.805, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[10, 20, 100]} />
        </group>
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-0.073, 0, 0.03]} rotation={[-Math.PI, 1.254, -Math.PI]} scale={[1.124, 1, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.073, 0, 0.03]} rotation={[-Math.PI, 1.254, -Math.PI]} scale={[1.124, 1, 1]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-0.054, 0, 0.024]} rotation={[-Math.PI, 1.254, -Math.PI]} scale={[1.124, 1, 1]} />
      <mesh geometry={nodes.Simple_GP_Layer.geometry} material={nodes.Simple_GP_Layer.material} position={[-0.104, 0, -0.066]} rotation={[-Math.PI, 1.254, -Math.PI]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} position={[-0.55, -0.729, 1.112]} rotation={[0, 0.018, 0]} scale={22.019} />
      <mesh geometry={nodes.Simple_GP_Layer001.geometry} material={nodes.Simple_GP_Layer001.material} position={[-0.123, 0, -0.231]} rotation={[0.013, 0, -0.01]} />
      <mesh geometry={nodes.Simple_GP_Layer002.geometry} material={nodes.Simple_GP_Layer002.material} position={[-0.254, -0.031, 0.067]} />
      <mesh geometry={nodes.Roundcube004.geometry} material={materials['Material.002']} position={[1.083, 1.08, 0.687]} scale={0.067} />
      <mesh geometry={nodes.Roundcube007.geometry} material={materials['Material.004']} position={[0.077, 1.591, -1.01]} scale={0.067} />
      <mesh geometry={nodes.Roundcube020.geometry} material={materials['Material.003']} position={[-0.223, 1.215, 1.268]} scale={0.067} />
      <mesh geometry={nodes.Roundcube023.geometry} material={materials['Material.005']} position={[0.277, 0.79, 0.943]} scale={0.067} />
      <group position={[-0.013, 1.933, 0.021]} rotation={[Math.PI / 2, 0, -0.302]} scale={[-0.132, -1.096, -0.135]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[1.053, 0.063, 0.645]} rotation={[3.127, 0.296, -0.042]} scale={[-0.107, -0.743, -0.109]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-0.543, 0.063, 1.197]} rotation={[3.127, 0.296, -0.042]} scale={[-0.098, -0.774, -0.1]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.GP_Layer.geometry} material={nodes.GP_Layer.material} position={[0.029, 0.13, 0.156]} rotation={[0, 0.37, 0]} scale={[1.008, 1.092, 1.008]} />
      <mesh geometry={nodes.Roundcube001.geometry} material={materials['Material.003']} position={[-0.248, 1.218, 1.345]} scale={0.067} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[1.712, -0.642, -0.73]} rotation={[0, 0.827, 0]} scale={[0.464, 0.069, 0.464]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.009']} position={[1.71, -0.552, -0.728]} rotation={[0, 0.827, 0]} scale={[0.377, 0.022, 0.377]} />
      <mesh geometry={nodes.Roundcube.geometry} material={materials['Material.010']} position={[1.921, 0.964, -0.501]} scale={0.068} />
      <mesh geometry={nodes.Roundcube006.geometry} material={materials['Material.014']} position={[2.176, 0.339, -0.718]} scale={0.074} />
      <mesh geometry={nodes.Roundcube008.geometry} material={materials['Material.013']} position={[2.151, -0.099, -0.841]} scale={0.074} />
      <mesh geometry={nodes.Roundcube010.geometry} material={materials['Material.011']} position={[2.008, -0.15, -0.616]} scale={0.074} />
      <mesh geometry={nodes.Roundcube018.geometry} material={materials['Material.012']} position={[-1.362, -0.694, 1]} scale={0.074} />
    </group>
  )
}

useGLTF.preload('/gingerbread.glb')
