/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ginger.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ginger.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Simple_GP_Layer002.geometry} material={nodes.Simple_GP_Layer002.material} position={[-0.22, -0.031, -0.182]} rotation={[0, -0.309, 0]} />
      <mesh geometry={nodes.Roundcube023.geometry} material={materials['Material.005']} position={[0.019, 0.79, 0.815]} rotation={[0, -0.309, 0]} scale={0.067} />
      <mesh geometry={nodes.Roundcube020.geometry} material={materials['Material.003']} position={[-0.556, 1.215, 0.971]} rotation={[0, -0.309, 0]} scale={0.067} />
      <mesh geometry={nodes.Roundcube018.geometry} material={materials['Material.012']} position={[-1.56, -0.694, 0.37]} rotation={[0, -0.309, 0]} scale={0.074} />
      <mesh geometry={nodes.Roundcube010.geometry} material={materials['Material.011']} position={[2.142, -0.15, -0.144]} rotation={[0, -0.309, 0]} scale={0.074} />
      <mesh geometry={nodes.Roundcube008.geometry} material={materials['Material.013']} position={[2.347, -0.099, -0.315]} rotation={[0, -0.309, 0]} scale={0.074} />
      <mesh geometry={nodes.Roundcube007.geometry} material={materials['Material.004']} position={[0.423, 1.591, -1.107]} rotation={[0, -0.309, 0]} scale={0.067} />
      <mesh geometry={nodes.Roundcube006.geometry} material={materials['Material.014']} position={[2.333, 0.339, -0.19]} rotation={[0, -0.309, 0]} scale={0.074} />
      <mesh geometry={nodes.Roundcube004.geometry} material={materials['Material.002']} position={[0.865, 1.08, 0.815]} rotation={[0, -0.309, 0]} scale={0.067} />
      <mesh geometry={nodes.Roundcube001.geometry} material={materials['Material.003']} position={[-0.604, 1.218, 1.037]} rotation={[0, -0.309, 0]} scale={0.067} />
      <mesh geometry={nodes.Roundcube.geometry} material={materials['Material.010']} position={[2.025, 0.964, -0.061]} rotation={[0, -0.309, 0]} scale={0.068} />
      <mesh geometry={nodes.GP_Layer.geometry} material={nodes.GP_Layer.material} position={[0.022, 0.13, -0.01]} rotation={[0, 0.061, 0]} scale={[1.008, 1.092, 1.008]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.009']} position={[1.893, -0.552, -0.341]} rotation={[0, 0.518, 0]} scale={[0.377, 0.022, 0.377]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Material} position={[1.895, -0.642, -0.343]} rotation={[0, 0.518, 0]} scale={[0.464, 0.069, 0.464]} />
      <group position={[-0.839, 0.063, 0.807]} rotation={[3.125, 0.605, -0.036]} scale={[-0.098, -0.774, -0.1]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.849, 0.063, 0.767]} rotation={[3.125, 0.605, -0.036]} scale={[-0.107, -0.743, -0.109]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.024, 1.933, -0.152]} rotation={[Math.PI / 2, 0, 0.007]} scale={[-0.132, -1.096, -0.135]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Vert.geometry} material={materials.Material} position={[1.898, -0.578, -0.382]} rotation={[-0.003, -1.231, -0.174]} scale={[0.109, 0.284, 0.2]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} position={[0.042, 0, 1.54]} rotation={[-Math.PI, 1.563, -Math.PI]} scale={[1.124, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/ginger.glb')
